const mongoose = require('mongoose');

const escalationSchema = new mongoose.Schema({
  patientId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  doctorId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  detectionId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'DetectionRecord',
    default: null,
  },
  sourceType: {
    type: String,
    enum: ['detection', 'vitals', 'mental_health', 'document'],
    required: true,
  },
  escalationType: {
    type: String,
    enum: ['immediate', 'priority', 'routine'],
    required: true,
  },
  summary: {
    condition: { type: String, default: '' },
    confidence: { type: Number, default: 0 },
    vitalsSnapshot: {
      heartRate: Number,
      systolic: Number,
      diastolic: Number,
      spo2: Number,
    },
    riskFactors: [{ type: String }],
    message: { type: String, default: '' },
  },
  status: {
    type: String,
    enum: ['pending', 'acknowledged', 'resolved'],
    default: 'pending',
  },
  autoGenerated: { type: Boolean, default: true },
  resolvedAt: { type: Date, default: null },
  doctorNotes: { type: String, default: '' },
}, {
  timestamps: true,
});

escalationSchema.index({ doctorId: 1, status: 1, createdAt: -1 });
escalationSchema.index({ patientId: 1, createdAt: -1 });

module.exports = mongoose.model('Escalation', escalationSchema);
