class Escalation {
  final String? id;
  final String patientId;
  final String doctorId;
  final String? detectionId;
  final String sourceType;
  final String escalationType;
  final EscalationSummary summary;
  final String status;
  final bool autoGenerated;
  final DateTime? createdAt;
  final DateTime? resolvedAt;
  final String doctorNotes;
  // Populated fields
  final String? patientName;
  final String? patientEmail;

  Escalation({
    this.id,
    required this.patientId,
    required this.doctorId,
    this.detectionId,
    required this.sourceType,
    required this.escalationType,
    required this.summary,
    this.status = 'pending',
    this.autoGenerated = true,
    this.createdAt,
    this.resolvedAt,
    this.doctorNotes = '',
    this.patientName,
    this.patientEmail,
  });

  factory Escalation.fromJson(Map<String, dynamic> json) {
    final patientData = json['patientId'];
    String patientId;
    String? patientName;
    String? patientEmail;

    if (patientData is Map<String, dynamic>) {
      patientId = patientData['_id']?.toString() ?? '';
      patientName = patientData['name'];
      patientEmail = patientData['email'];
    } else {
      patientId = patientData?.toString() ?? '';
    }

    return Escalation(
      id: json['_id']?.toString(),
      patientId: patientId,
      doctorId: json['doctorId']?.toString() ?? '',
      detectionId: json['detectionId']?.toString(),
      sourceType: json['sourceType'] ?? '',
      escalationType: json['escalationType'] ?? 'routine',
      summary: EscalationSummary.fromJson(json['summary'] ?? {}),
      status: json['status'] ?? 'pending',
      autoGenerated: json['autoGenerated'] ?? true,
      createdAt: json['createdAt'] != null ? DateTime.tryParse(json['createdAt']) : null,
      resolvedAt: json['resolvedAt'] != null ? DateTime.tryParse(json['resolvedAt']) : null,
      doctorNotes: json['doctorNotes'] ?? '',
      patientName: patientName,
      patientEmail: patientEmail,
    );
  }

  Map<String, dynamic> toJson() => {
        'patientId': patientId,
        'doctorId': doctorId,
        if (detectionId != null) 'detectionId': detectionId,
        'sourceType': sourceType,
        'escalationType': escalationType,
        'summary': summary.toJson(),
      };

  bool get isImmediate => escalationType == 'immediate';
  bool get isPriority => escalationType == 'priority';
  bool get isPending => status == 'pending';
}

class EscalationSummary {
  final String condition;
  final double confidence;
  final VitalsSnapshot? vitalsSnapshot;
  final List<String> riskFactors;
  final String message;

  EscalationSummary({
    this.condition = '',
    this.confidence = 0,
    this.vitalsSnapshot,
    this.riskFactors = const [],
    this.message = '',
  });

  factory EscalationSummary.fromJson(Map<String, dynamic> json) =>
      EscalationSummary(
        condition: json['condition'] ?? '',
        confidence: (json['confidence'] as num?)?.toDouble() ?? 0,
        vitalsSnapshot: json['vitalsSnapshot'] != null
            ? VitalsSnapshot.fromJson(json['vitalsSnapshot'])
            : null,
        riskFactors: List<String>.from(json['riskFactors'] ?? []),
        message: json['message'] ?? '',
      );

  Map<String, dynamic> toJson() => {
        'condition': condition,
        'confidence': confidence,
        if (vitalsSnapshot != null) 'vitalsSnapshot': vitalsSnapshot!.toJson(),
        'riskFactors': riskFactors,
        'message': message,
      };
}

class VitalsSnapshot {
  final double? heartRate;
  final double? systolic;
  final double? diastolic;
  final double? spo2;

  VitalsSnapshot({this.heartRate, this.systolic, this.diastolic, this.spo2});

  factory VitalsSnapshot.fromJson(Map<String, dynamic> json) => VitalsSnapshot(
        heartRate: (json['heartRate'] as num?)?.toDouble(),
        systolic: (json['systolic'] as num?)?.toDouble(),
        diastolic: (json['diastolic'] as num?)?.toDouble(),
        spo2: (json['spo2'] as num?)?.toDouble(),
      );

  Map<String, dynamic> toJson() => {
        if (heartRate != null) 'heartRate': heartRate,
        if (systolic != null) 'systolic': systolic,
        if (diastolic != null) 'diastolic': diastolic,
        if (spo2 != null) 'spo2': spo2,
      };
}
