const express = require('express');
const auth = require('../middleware/auth');
const Escalation = require('../models/Escalation');

const router = express.Router();

// POST /api/escalations - Create a new escalation
router.post('/', auth, async (req, res) => {
  try {
    const {
      patientId, doctorId, detectionId, sourceType,
      escalationType, summary,
    } = req.body;

    const escalation = await Escalation.create({
      patientId,
      doctorId,
      detectionId: detectionId || null,
      sourceType,
      escalationType,
      summary: summary || {},
      autoGenerated: true,
    });

    res.status(201).json({ escalation });
  } catch (error) {
    console.error('Escalation create error:', error);
    res.status(500).json({ message: 'Server error creating escalation' });
  }
});

// GET /api/escalations/doctor/:doctorId - Get doctor's escalation queue
router.get('/doctor/:doctorId', auth, async (req, res) => {
  try {
    const { status } = req.query;
    const filter = { doctorId: req.params.doctorId };
    if (status) filter.status = status;

    const escalations = await Escalation.find(filter)
      .sort({ createdAt: -1 })
      .populate('patientId', 'name email')
      .limit(50);

    res.json({ escalations });
  } catch (error) {
    console.error('Escalation fetch error:', error);
    res.status(500).json({ message: 'Server error fetching escalations' });
  }
});

// GET /api/escalations/patient/:patientId - Get patient's escalation history
router.get('/patient/:patientId', auth, async (req, res) => {
  try {
    const escalations = await Escalation.find({ patientId: req.params.patientId })
      .sort({ createdAt: -1 })
      .populate('doctorId', 'name')
      .limit(50);

    res.json({ escalations });
  } catch (error) {
    console.error('Escalation fetch error:', error);
    res.status(500).json({ message: 'Server error fetching escalations' });
  }
});

// PUT /api/escalations/:id/acknowledge - Acknowledge escalation
router.put('/:id/acknowledge', auth, async (req, res) => {
  try {
    const escalation = await Escalation.findByIdAndUpdate(
      req.params.id,
      { status: 'acknowledged' },
      { new: true },
    );
    if (!escalation) return res.status(404).json({ message: 'Escalation not found' });
    res.json({ escalation });
  } catch (error) {
    res.status(500).json({ message: 'Server error' });
  }
});

// PUT /api/escalations/:id/resolve - Resolve escalation
router.put('/:id/resolve', auth, async (req, res) => {
  try {
    const { doctorNotes } = req.body;
    const escalation = await Escalation.findByIdAndUpdate(
      req.params.id,
      {
        status: 'resolved',
        resolvedAt: new Date(),
        doctorNotes: doctorNotes || '',
      },
      { new: true },
    );
    if (!escalation) return res.status(404).json({ message: 'Escalation not found' });
    res.json({ escalation });
  } catch (error) {
    res.status(500).json({ message: 'Server error' });
  }
});

module.exports = router;
